### ISSUE TITLE
Counts 7 steps instead of 1

### ISSUE THREAD

**Issue by samweisgamdschie** [j4velin/Pedometer#100]
OK my SMG900-F Galaxy s5 with Cyanogenmod 13.0 (Android 6.0.1) it counts about 7 steps every step i make. On cm 12.1 it works like a charm.

I have to add, on the other hand it does not count about the half of my steps. I dont know why and when..

**Comment by j4velin** [comment]
The app just reads the data from the device sensor, it has no influence on the accuracy of the data provided by the sensor
