### ISSUE TITLE
how to find your Pedometer in the Play Store??

### ISSUE THREAD

**Issue by wjcroft** [j4velin/Pedometer#101]
Any suggestions on how to locate your app? There are seemingly hundreds of apps with 'pedometer' in the title. Read a nice review of your app here,

http://appcrawlr.com/android/pedometer-22#authors-description

Regards,

William Croft

**Comment by TPS** [comment]
Links @ bottom of https://github.com/j4velin/Pedometer:
> <a href="https://play.google.com/store/apps/details?id=de.j4velin.pedometer">
  <img alt="Get it on Google Play"
       src="https://developer.android.com/images/brand/en_generic_rgb_wo_45.png" />
</a><a href="https://f-droid.org/repository/browse/?fdid=de.j4velin.pedometer&fdpage=35">
  <img alt="Get it on F-Droid"
       src="https://cloud.githubusercontent.com/assets/12447257/8024903/ce8dca32-0d44-11e5-95b0-e97d1d027351.png" /></a>
lead to https://play.google.com/store/apps/details?id=de.j4velin.pedometer & https://f-droid.org/repository/browse/?fdid=de.j4velin.pedometer
