### ISSUE TITLE
Provide less frustrating way to change the daily goal

### ISSUE THREAD

**Issue by KopfKrieg** [j4velin/Pedometer#104]
The first entry in the settings page allows to change the daily goal, but only in steps of 1. This is really frustrating if I want, e.g., a daily goal of 8000.

I see two possibilities:
 - Increase the step size of the NumberPicker (e.g. Min=100 Steps, Max=100000 Steps, in steps of 100 in between)
 - Or change to a normal text/number input field, where I can input any number i want (in range from 1 to 100000)

(I'd provide a patch, but I can't get the project working on Android Studio)

**Comment by j4velin** [comment]
You can just tap on the number to open the keyboard and enter any number directly

**Comment by KopfKrieg** [comment]
Whoops, somehow I missed that. Thank you :)
