### ISSUE TITLE
Behaviour change of AlarmManager.set() since API 19

### ISSUE THREAD

**Issue by frankFic** [j4velin/Pedometer#111]
Hi,

I have noticed that in SensorListener.java API [AlarmManager.set(int, long, PendingIntent)](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent)) is used to schedule services to save the step count and restart sensor services.

According to the document, after API 19, the scheduled event will not be triggered immediately at the scheduled time and will be delayed by the operating system. After API 19, new API like setExact() and setWindow() were introduced to trigger the tasks in time.

I think it would be especially important to not use the old API when restart the sensor service. Hope this information can help.

Thx.

**Comment by j4velin** [comment]
Hey, I'm aware of that change but I dont think the app needs to use exact alarms anywhere
