### ISSUE TITLE
Reactive database

### ISSUE THREAD

**Issue by erluxman** [j4velin/Pedometer#112]
Can I send A PR with those database implementation in ROOM so that we wont have to implement sensor listener to every UI components ?

**Comment by j4velin** [comment]
Of course you can send a PR - I can't guarantee to merge it but I'm curious
how that would eliminate the implementation of the sensor listener in the
UI (note that the sensor listener for the UI updates more frequent and does
not use batch updates)


Laxman Bhattarai <notifications@github.com> schrieb am Di., 14. Nov. 2017
um 13:09 Uhr:
