### ISSUE TITLE
wrong total count after fly

### ISSUE THREAD

**Issue by mehmetulukaya** [j4velin/Pedometer#114]
Hello,

I am using pedometer in a samsung device but I noticed counter of total summed wrong.
This event happened after flight I think reason is local timing I was passed midnight on the plane and when arrived phone changed the time and time passed same day again.

Is it possible to avoid this possibilities?

Also I have samsung healt software to it counted as usualy.

Best regards

**Comment by j4velin** [comment]
Duplicate: https://github.com/j4velin/Pedometer/issues/89
