### ISSUE TITLE
LOGO DESIGN PROPOSAL

### ISSUE THREAD

**Issue by Tobaloidee** [j4velin/Pedometer#117]
Hi Sir j4velin, I am proposing a logo/icon design for Pedometer.I hope you would like and consider it. Thanks a lot! I'm willing to make adjustments to your liking if ever. Here is the link Sir. 

https://utopian.io/utopian-io/@tobaloidee/my-icon-logo-design-proposal-for-pedometer

Thanks, 
Tobaloidee

**Comment by j4velin** [comment]
Thanks, looks good!

tobaloidee <notifications@github.com> schrieb am So., 18. März 2018, 02:30:

**Comment by Tobaloidee** [comment]
I'm glad that you liked it Sir! just let me know if you need some adjustments or changes..Thanks so much! i'll keep in touch.

**Comment by MisterY** [comment]
Man, you really have some good ideas!
