### ISSUE TITLE
Changing the number picker dialog on "goal" settings to custom dialog? 

### ISSUE THREAD

**Issue by sukibeww** [j4velin/Pedometer#128]
i think using number picker dialog to modify the goal is rather ineffective, maybe a custom dialog that asserts user input to number only will be a better option to modify user's goal.  

I'm a CS student with an assignment to approach and try to contribute to an Open-source community, sorry if this is a waste of time. thank you...

PS: great application 👍, i learned a lot from it   

-

**Comment by j4velin** [comment]
Feel free to submit a pull request and I'll merge it if it makes sense
