### ISSUE TITLE
Translate Google Play description

### ISSUE THREAD

**Issue by naXa777** [j4velin/Pedometer#132]
I'd like to contribute Russian translation for your Google Play application entry. Currently, it's in English https://play.google.com/store/apps/details?id=de.j4velin.pedometer&hl=ru

Can you guide me on this? I think having a file in this repo with a description written in different languages is the right way.

**Comment by j4velin** [comment]
Good idea, just add the text here: https://github.com/j4velin/Pedometer/blob/master/playstore_description.txt
