### ISSUE TITLE
App not running in background on Android Pie

### ISSUE THREAD

**Issue by laama1** [j4velin/Pedometer#136]
Is anybody else having issues with Android Pie?
I have LineageOS 16 beta/unofficial on Samsung galaxy s5.
App runs fine when on foreground. Does not count steps on background.

**Comment by marasm76** [comment]
I'm also having this issue. Either doesn't count or counts sporadically. Android 9 Pie on a Nokia 6.1.

**Comment by laama1** [comment]
Updated to latest version from f-droid recently and my Android is many updates newer, Pedometer now works in background. I think this issue is solved now.
