### ISSUE TITLE
Crash v1.5.10 on Nexus 5 with LOS 14.1

### ISSUE THREAD

**Issue by rogers1106** [j4velin/Pedometer#139]
Hello, the app crashes immediately after starting it or tapping the notification. Clearing cache or new install does not help. v1.5.8 does not have this problem.

**Comment by j4velin** [comment]
Should be fixed with https://github.com/j4velin/Pedometer/commit/a3db68561c5d87b5b704467ddf40b1e43aa680fd

**Comment by rogers1106** [comment]
Confirmed. Thanks a lot.

________________________________
Von: Thomas Hoffmann <notifications@github.com>
Gesendet: Dienstag, 2. Juli 2019 07:22
An: j4velin/Pedometer
Cc: Roger S.; Author
Betreff: Re: [j4velin/Pedometer] Crash v1.5.10 on Nexus 5 with LOS 14.1 (#139)

Should be fixed with a3db685
