### ISSUE TITLE
Question about social/friends

### ISSUE THREAD

**Issue by arnaudmm** [j4velin/Pedometer#146]
Hello,

First of all thank you for developing this app, this is rly cool :)
I was wondering if I can compete with friends of mine with your app? I have connected my app to google play, but I don't see how I can "add" them to see their score easily.

Am I missing something?

If the feature is not implemented yet, I would be interested to participate and help to do it.

**Comment by j4velin** [comment]
If you sign in with Google Play Games, you should be able to see your contacts on the leaderboards
