### ISSUE TITLE
Use text field for 'Set goal' instead of scrolling number wheel

### ISSUE THREAD

**Issue by Clef-0** [j4velin/Pedometer#148]
![Screenshot_20200625-154253_Pedometer](https://user-images.githubusercontent.com/10343775/85741814-a4bab480-b6fa-11ea-8656-cd82f3a8e9ec.png)
The 'Set goal' window currently uses a scrolling number field, which means it takes a while to change my goal from 10,000 to 20,000, I think most people would find a normal text input more useful.

**Comment by j4velin** [comment]
That number in the middle should be a text field (at least it is on stock Android). You can just tap on it to open the keyboard
