### ISSUE TITLE
Feature request: distance traveled

### ISSUE THREAD

**Issue by FBachofner** [j4velin/Pedometer#152]
Awesome app!  Thank you.

I am hoping you could add a "distance traveled" feature.

To make is more accurate it would also be great if a customized step length could be entered.  It would be good, of course, to have an initial default (i.e. average) step length for people who don't care to edit this.

Also, it would be great to be able to pick units (i.e. miles, kilometers . . . maybe "leagues" if you want to be funny! :-)

This would help a lot for people who want to have an idea how far they traveled without installing a full-blown fitness activity tracker.

Thank you for your consideration.

**Comment by j4velin** [comment]
If you click on the pie bar once, it should change between number of steps taken and distanced walked (calculated based on the step count and the configured step length)
