### ISSUE TITLE
Hiow

### ISSUE THREAD

**Issue by RudrakshG** [j4velin/Pedometer#154]
How can I run it on pc after zip file installation?

**Comment by RudrakshG** [comment]
Kindly reply fast

**Comment by RudrakshG** [comment]
Yes yes. With the local server. Or with any software.

**Comment by RudrakshG** [comment]
So kindly tell

**Comment by j4velin** [comment]
It is a pedometer app. You don't run a pedometer on your desktop PC. It makes no sense
