### ISSUE TITLE
Copycat / Clone on Google Play

### ISSUE THREAD

**Issue by Poussinou** [j4velin/Pedometer#160]
Hi,

Below you can find a copycat of your app from [this developer](https://play.google.com/store/apps/developer?id=Doshacorp) :

https://play.google.com/store/apps/details?id=de.j4velin.tembea

Maybe you can send a DMCA request to Google to take it down?

**Comment by j4velin** [comment]
Thanks, I'll try to contact the "developer" of the clone

Poussinou ***@***.***> schrieb am Sa., 14. Aug. 2021, 02:01:
