### ISSUE TITLE
Open pedometer.csv with LibreOffice spreadsheet 

### ISSUE THREAD

**Issue by xabelgul** [j4velin/Pedometer#168]
I have been using this App for a few weeks now and I congratulate you for its simple and effective operation.
I have a backup of my steps in a pedometer.csv file.
I try to open it with the LibreOffice spreadsheet but I don't see how to treat the data in the first column, e.g. 1657836000000
I guess it represents the date or the date and time but I can't find the relation to be able to handle it in a usual format.
Does anyone know how to do it?
Thanks

**Comment by opensource21** [comment]
I mean it's epochtime in milliseconds. With this google should provide a complete solution.

**Comment by xabelgul** [comment]
That's the solution!

Thank you very much
