### ISSUE TITLE
Support for google fit?

### ISSUE THREAD

**Issue by jeremyfrench** [j4velin/Pedometer#55]
Google fit will be coming out soon. https://developers.google.com/fit/preview It would be nice if this app could support it. Is this planned?

**Comment by Ofergov** [comment]
Does not work for me. Nexus 5 android 5.1. I see in google fit that the app is connected. I have Endomondo connected too, while endomondo pushes my runs to google fit pedometer does not. I have location history disabled so I have no activitiy in days I don't run. What can be done?
