### ISSUE TITLE
The record of steps is ridiculous!

### ISSUE THREAD

**Issue by ghost** [j4velin/Pedometer#62]
### I set 0.95 meter per step in the Pedometer, So I walked 16.91285 km during several hours.  Is it ridiculous?

![screenshot_2015-01-09-15-10-48](https://cloud.githubusercontent.com/assets/4438309/5676510/e7cf0eaa-9811-11e4-88d7-30f2fdacaae5.png)
![screenshot_2015-01-09-15-14-47](https://cloud.githubusercontent.com/assets/4438309/5676534/5474ce78-9812-11e4-8a99-dea0615875e9.png)

**Comment by j4velin** [comment]
I dont think 17.800 steps are ridiculous

**Comment by j4velin** [comment]
Did you do anything else with your phone? Going by car / train or something? Note that I have no influence on the sensors sensitivity

**Comment by youlansedeninan** [comment]
I don't know why.But it seems become normal.
![screenshot_2015-01-15-10-42-53](https://cloud.githubusercontent.com/assets/4438309/5751751/700a78aa-9ca3-11e4-95a0-fe1d1ce39914.png)
Last Thu. and Fri. the steps is unbelievable. But this week , it works good.

**Comment by Jabe** [comment]
Hi there,

similar issue after upgrading to Lollipop. Step counting seems kind of random now. Each step is counted 1-100 times. Tried reboot, wipe data, reinstall, not resolved.

Been using this app for a while now (on S4 running CM11) and tracked about 1.5 Megasteps ;) , but decided to switch to a (unofficial) Lollipop-based Google Play Edition Rom. So obviously this could be Rom or Kernel related, but maybe an issue with Lollipop?

Cheers

**Comment by j4velin** [comment]
Works fine on my Nexus 5 with AOSP Lollipop

**Comment by Jabe** [comment]
I've been playing around with this. I checked out GPS Status Pro, which reads the HW-pedometer value as well and shows the same bad behaviour. Then I installed yet another HW-pedometer app and now all three apps magically count correctly. When I uninstall the new app, both this app and GPS Status immediately start counting wrong again. So, uninstall all pedometers and keep only GPS Status, counts badly, install the other pedometer, fixes it. So... yeah, shared resource acting weird, what a pleasure.

**Comment by evsh** [comment]
@Jabe, I have exactly the same problem with S4 and CM 12.1. What this another HW-pedometer app is, please?

**Comment by sniperle** [comment]
Having the same problem on LG G2 with CM 12, millions of steps are shown to me ;-)

![million steps](https://cloud.githubusercontent.com/assets/3104188/7364563/499c7f7a-ed88-11e4-9797-849cdeedb813.png)

**Comment by matthiasbeyer** [comment]
Oneplusone here, had 300,000 steps yesterday. :curly_loop: ... after bringing my phone to low-power mode...

**Comment by matthiasbeyer** [comment]
Can report: 17,8k steps is not that much. When going for a walk, you can get to 17k! My record one day is 21k. Normal days, though, I'm around 9-11k!

300k tough is a bug. If the app crashes, it reports wrong numbers!
