### ISSUE TITLE
Missing repository definition

### ISSUE THREAD

**Issue by krt16s** [j4velin/Pedometer#71]
I think you are missing a repository definition like...

````
repositories {
	jcenter()
	mavenCentral()
}
`````
...for the actual app-dependencies. The overall structure should look like:
````
buildscript {
    repositories {}
    dependencies {}
}

apply plugin: 'com.android.application'

android {}
repositories {}
dependencies {}
````

**Comment by j4velin** [comment]
Fixed in https://github.com/j4velin/Pedometer/commit/3c65680da9898d4c915e7228945e493ccbcc6588y error when building the app?
