### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by pavestnavi** [j4velin/Pedometer#75]
Pedo doesn't really mean feet, it means kids. You're measuring kids. That's fucking weird.

And it doesn't even work, it's just tracking steps or something. I tried to measure my nephew with it and the app was all like "you've walked 10 steps in the last 10 days"

I couldn't measure shit.

**Comment by j4velin** [comment]
"A pedometer is a device, usually portable
andelectronic or electromechanical, that counts each step a person takes by
detecting themotion of the person's hands or hips." from
https://en.m.wikipedia.org/wiki/Pedometer
