### ISSUE TITLE
Export format: What kind of timestamp is the data?

### ISSUE THREAD

**Issue by matthiasbeyer** [j4velin/Pedometer#79]
Hey,

I want to use the data I can export with the export functionality to create some graphics for my walking behaviour. Though I don't know what kind of timestamp you are using. It is not Unix timestamp, as this

```bash
$ date --date "@1454281200000"
So 3. Mai 10:00:00 CEST 48054
```

shows (`1454281200000` is a timestamp from the export).

What kind of timestamp are you using?

**Comment by j4velin** [comment]
Milliseconds since 1970

**Comment by matthiasbeyer** [comment]
Why would you pick such a weird export format? Why not simple `<YYYY>-<MM>-<DD>`? Is there any technical reason for this?

**Comment by j4velin** [comment]
I dont think it weirder than any other date format. I mean, you nearly tried it as a unix timestamp to begin with

**Comment by matthiasbeyer** [comment]
Yes, but it is neither Unix timestamp nor any other ... known format. I'd expect at least unix timestamp when seeing such values... but instead I had to ask here how to parse my data...

**Comment by ogr3** [comment]
It's a known format. It's a Java standard timestamp (https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#currentTimeMillis())
