### ISSUE TITLE
Widget not updating on S7edge

### ISSUE THREAD

**Issue by jroldroyd** [j4velin/Pedometer#84]
The subject says it. Installed version 1.4.3 from F-Droid, added a widget, widget remains static at the count it was when added, but touching the widget to open the app shows that the counter has indeed incremented.

**Comment by j4velin** [comment]
The widget does not update in real time with every step as this would use
too many system resources

jroldroyd <notifications@github.com> schrieb am Mi., 8. Juni 2016, 09:55:

**Comment by jroldroyd** [comment]
I must update this. The widget has updated in fact, but it is not syncing frequently. At the moment, the widget value is just under 250 paces behind the value shown when I open the app.

I am not sure what triggers a widget update, but it does not appear to be frequently enough.

**Comment by j4velin** [comment]
I'll make the widget update more often soon (see https://github.com/j4velin/Pedometer/issues/97)
