### ISSUE TITLE
No R.java file in project

### ISSUE THREAD

**Issue by dute2** [j4velin/Pedometer#88]
theres no R.java file in your project

**Comment by Odaym** [comment]
If you like, watch this video I made about implementing a proper Pedometer on Android https://youtu.be/8Wku0jvnXEA and it goes over this and other libraries that attempt to do this, hope it helps you!

**Comment by dute2** [comment]
it is not a solution. i need R.java file for it

**Comment by Odaym** [comment]
Good luck

**Comment by j4velin** [comment]
R is an automatically generated class when you build the project

**Comment by dute2** [comment]
yeah i know but some files missing . so i need original R.java file of this project

**Comment by j4velin** [comment]
Sorry, but that doesnt make sense. If you cant build the app because some files are missing (which?) then adding my R.java wont help

**Comment by dute2** [comment]
ok. thanx . actually i am newbie in this field. so more chances are m doing something wrong. but i will be very thankful to you if you just send R.java for it
