### ISSUE TITLE
Update the widget more frequently

### ISSUE THREAD

**Issue by nvx2004** [j4velin/Pedometer#97]
Would it please be possible to update the widget more frequently? For example each time the phone is unlocked, each time one opens the app, etc., but not more than once, say, every 10 minutes. As of the current version (1.4.9), the widget updates roughly three or four times a day which I feel is rather insufficient given the fact that it is supposed to be informative.

Thank you. :)

**Comment by j4velin** [comment]
On my todo list

**Comment by j4velin** [comment]
Should work better now: https://github.com/j4velin/Pedometer/commit/1044b1e6e46153a2d7b62c69294aab0b04eebde0
