### ISSUE TITLE
Old version on F-Droid

### ISSUE THREAD

**Issue by sniperle** [j4velin/Pedometer#99]
The version on F-Droid is outdated.
As of today (2017-04-23) it's still 1.4.3

**Comment by j4velin** [comment]
Sorry, but you need to contact the F-Droid guys for that. I don't build or upload anything to F-Droid

**Comment by sniperle** [comment]
Ah OK, then I will have a look at the F-Droid page. 

Thought you'd be interested in that the latest version is available on F-Droid, since you use the "Get in on F-Droid" Download button on your site.

**Comment by mimi89999** [comment]
@j4velin Please tag all feature releases so that the F-Droid bot could automatically update the metadata file.

**Comment by MarcRdC** [comment]
@j4velin Last advice from @mimi89999 still holds. If you tag your releases here on GitHub, they will be automatically detected and built by F-Droid. Thank you!

**Comment by j4velin** [comment]
I'll try to keep that in mind

MarcRdC <notifications@github.com> schrieb am Di., 6. Nov. 2018, 09:49:
